apiVersion: 1

policies:
  - orgId: 1
    receiver: Discord Alerting
    group_by:
      - alertname
      - severity
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      # Alertes critiques → Discord + Telegram + Email
      - receiver: Discord Alerting
        matchers:
          - severity = critical
        continue: true
      - receiver: Telegram Alerting
        matchers:
          - severity = critical
        continue: true
      - receiver: Email Alerting
        matchers:
          - severity = critical
      # Alertes warning → Discord uniquement
      - receiver: Discord Alerting
        matchers:
          - severity = warning
